
package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "distance", targetNamespace = "tns:distance", wsdlLocation = "http://www-student.it.uts.edu.au/~brookes/gns/distance.wsdl")
public class Distance
    extends Service
{

    private final static URL DISTANCE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.Distance.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.Distance.class.getResource(".");
            url = new URL(baseUrl, "http://www-student.it.uts.edu.au/~brookes/gns/distance.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www-student.it.uts.edu.au/~brookes/gns/distance.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DISTANCE_WSDL_LOCATION = url;
    }

    public Distance(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Distance() {
        super(DISTANCE_WSDL_LOCATION, new QName("tns:distance", "distance"));
    }

    /**
     * 
     * @return
     *     returns DistancePortType
     */
    @WebEndpoint(name = "distancePort")
    public DistancePortType getDistancePort() {
        return super.getPort(new QName("tns:distance", "distancePort"), DistancePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistancePortType
     */
    @WebEndpoint(name = "distancePort")
    public DistancePortType getDistancePort(WebServiceFeature... features) {
        return super.getPort(new QName("tns:distance", "distancePort"), DistancePortType.class, features);
    }

}
