
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "distancePortType", targetNamespace = "tns:distance")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DistancePortType {


    /**
     * Send a greeting message. For testing purposes.
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "tns:distance#sayHello")
    @WebResult(name = "greeting", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "tns:distance", className = "client.SayHelloRequestType")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "tns:distance", className = "client.SayHelloResponseType")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * Calculate the distance between two locations identified by their geographic coordinates (latitude and longitude).
     * 
     * @param parameters
     * @return
     *     returns client.GetDistanceResponseType
     */
    @WebMethod(action = "tns:distance#getDistance")
    @WebResult(name = "getDistanceResponse", targetNamespace = "tns:distance", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetDistanceResponseType getDistance(
        @WebParam(name = "getDistance", targetNamespace = "tns:distance", partName = "parameters")
        GetDistanceRequestType parameters);

}
